@startuml Database Diagram

<style>
title {
  HorizontalAlignment right
  FontSize 24
'   FontColor blue
}

header {
  HorizontalAlignment center
  FontSize 16
'   FontColor purple
  FontStyle bold
}

' footer {
'   HorizontalAlignment left
'   FontSize 28
'   FontColor red
' }

legend {
  FontSize 30
  BackGroundColor yellow
  Margin 30
  Padding 50
}

caption {
  FontSize 32
}
</style>

' Определение стилей для элементов базы данных с одинаковыми отступами
!define PK(x)     <b><color:#b8861b>PK</color>   x</b>
!define FK(x)     <b><color:#aaaaaa>FK</color>   x</b>
!define FPK(x)    <b><color:#b8861b>FPK</color> x</b>
!define column(x) <b><color:#efefef><&media-record></color>     x</b>
!define table(x)  entity x << (T, white) >>

' Настройка стилей для всей диаграммы
skinparam {
    PackageStyle rectangle
    ArrowColor #2688d4
    ArrowThickness 1.5
    EntityBorderThickness 1.5
    EntityBorderColor #2688d4
    EntityBackgroundColor white
    EntityFontColor black
    EntityFontSize 14
    padding 4
    roundCorner 10
    defaultTextAlignment left
    shadowing false
}

' header some header

' footer some footer

title Database Diagram

' caption This is caption

' legend
' The legend
' end legend

' Определение таблиц базы данных
table(dictionaries) {
    PK(id): INT AUTO_INCREMENT
    column(title): TEXT NOT NULL
    column(guid): TEXT NOT NULL
}

table(words) {
    PK(id): INT AUTO_INCREMENT
    column(words): TEXT NOT NULL
    column(transcription): TEXT
    column(translation): TEXT NOT NULL
    column(part_of_speech): TEXT NOT NULL
    column(language): TEXT NOT NULL DEFAULT 'en'
    column(level): TEXT NOT NULL DEFAULT 'A1'
    column(explanation): TEXT
    column(is_irregular): BOOLEAN
    column(irregular_forms): TEXT
    column(examples): TEXT
    column(last_review_date): TIMESTAMP
    column(review_count): INT
    column(easiness): INT
    column(audio): BLOB
    column(audio2): BLOB
    column(audio3): BLOB
    --
    FK(dictionary_id): INT
}

table(units) {
    PK(id): INT AUTO_INCREMENT
    column(title): TEXT NOT NULL
    column(description): TEXT
    column(guid): TEXT NOT NULL
}

table(unit_words) {
    FPK(unit_id): INT NOT NULL
    FPK(word_id): INT NOT NULL
}

table(grammar_tests) {
    PK(id): INT AUTO_INCREMENT
    column(title): TEXT NOT NULL
    column(mask): TEXT
    column(last_review_date): TIMESTAMP
    column(review_count): INT
    column(guid): TEXT NOT NULL
}

table(grammar_test_questions) {
    PK(id): INT AUTO_INCREMENT
    column(sentence): TEXT NOT NULL
    column(translation): TEXT NOT NULL
    column(answers): TEXT NOT NULL
    column(correct_answer): TEXT NOT NULL
    --
    FK(test_id): INT
}

table(grammar_topics) {
    PK(id): INT AUTO_INCREMENT
    column(title): TEXT NOT NULL
    column(description): TEXT
    column(content): TEXT NOT NULL
    column(guid): TEXT NOT NULL
    --
    FK(topic_id): INT
}

table(grammar_topic_tests) {
    FPK(topic_id): INT NOT NULL
    FPK(test_id): INT NOT NULL
}

' Определение связей между таблицами
dictionaries ||--o{ words
units ||--o{ unit_words
unit_words }o--|| words
grammar_tests ||--o{ grammar_test_questions
grammar_topic_tests ||--o{ grammar_tests
grammar_topic_tests ||--o{ grammar_topics
grammar_topics ||--o{ grammar_topics : parent > child

@enduml